#!/bin/bash

echo "$WSPR_TIMESTAMP $WSPR_REPORTER => $WSPR_CALLSIGN $WSPR_BAND"

echo "\"$WSPR_TIMESTAMP\";\"$WSPR_REPORTER\";\"$WSPR_CALLSIGN\";\"$WSPR_BAND\";\"$WSPR_REPORTER_COUNTRY\";\"$WSPR_CALLSIGN_COUNTRY\"" >> /tmp/log.txt
